### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jpalmeida** [matheuslenke/Tonto#5]
A simple typo in the error message: "There is a ciclic specialization. Please review all Elements specializations and generalizationSets from your model"
"ciclic" should read "cyclic"

Further, "Elements specializations and generalizationSets" sounds weird. I'd suggest "specializations (including those in generalization sets)"

**Comment by matheuslenke** [comment]
Fixed on PR #6. The message now is:
"There is a cyclic specialization. Please review all Elements specializations from your model (including those in generalization sets)"
